'use client';
import {useMemo,useRef,useState,type CSSProperties} from 'react';
import map from '@/data/research-map.json';
import profile from '@/data/profile.json';
import {traceLineage} from '@/lib/research-graph';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {ToggleGroup,ToggleGroupItem} from '@/components/ui/toggle-group';

const themes=[{key:'all',label:'All research',tags:[],color:'#d4ef8a'},{key:'qual',label:'AI4Qual',tags:['qual'],color:'#b1a0ff'},{key:'affect',label:'Affect & VR',tags:['affect','vr','embodiment'],color:'#ff91b4'},{key:'home',label:'Agents & safety',tags:['home','agents','safety'],color:'#63d5bb'},{key:'access',label:'Accessibility',tags:['access','privacy'],color:'#ffd18c'},{key:'social',label:'Social computing',tags:['social'],color:'#85bbff'},{key:'trust',label:'Trust & learning',tags:['trust','edu'],color:'#a5c8f4'},{key:'reasoning',label:'LLM reasoning',tags:['reasoning','llmeval'],color:'#b1a0ff'}];
const works=[...profile.publications,...profile.projects];
const colors:Record<string,string>={'#5B3FBF':'#b1a0ff','#C2426B':'#ff91b4','#1F7A6B':'#63d5bb','#B4711A':'#ffd18c','#2E6FB7':'#85bbff','#8A79E8':'#b1a0ff'};
const arcs=[{key:'sys',label:'Systems',sub:'Tools · datasets · defences'},{key:'evd',label:'Evidence',sub:'People · practices · evaluation'},{key:'con',label:'Consequences',sub:'Trust · ethics · institutions'}];
export default function ResearchMap(){
 const [theme,setTheme]=useState('all');const [query,setQuery]=useState('');const [selected,setSelected]=useState('arXiv.2');const [zoom,setZoom]=useState(1);const [view,setView]=useState('map');const viewport=useRef<HTMLDivElement>(null);
 const active=themes.find(t=>t.key===theme)!;
 const filtered=map.nodes.filter(n=>{const p=works.find(p=>p.id===n.publicationId)!;return (theme==='all'||active.tags.some(t=>n.tags.includes(t)))&&`${p.title} ${p.authors} ${p.venue} ${p.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase());});
 const visible=new Set(filtered.map(n=>n.key));
 const {ancestors,descendants}=useMemo(()=>traceLineage(selected,map.edges),[selected]);
 const selectedNode=map.nodes.find(n=>n.key===selected)!;const paper=works.find(p=>p.id===selectedNode.publicationId)!;
 const layout=useMemo(()=>{let y=66;const positions:Record<string,{x:number,y:number}>= {};const bands:{label:string;sub:string;y:number;height:number}[]=[];
 for(const arc of arcs){const group=filtered.filter(n=>n.arc===arc.key);if(!group.length)continue;const start=y;let largest=1;for(const year of [2022,2023,2024,2025,2026]){const nodes=group.filter(n=>{const p=works.find(p=>p.id===n.publicationId)!;return p.kind.includes(String(year))}).sort((a,b)=>a.y-b.y);largest=Math.max(largest,nodes.length);nodes.forEach((n,i)=>positions[n.key]={x:162+(year-2022)*208,y:y+22+i*68});}const height=largest*68+40;bands.push({label:arc.label,sub:arc.sub,y:start,height});y+=height+12;}return {positions,bands,height:Math.max(330,y+14)}},[filtered.map(n=>n.key).join('|')]);
 function pick(key:string){setSelected(key)}
 function reset(){setTheme('all');setQuery('');setZoom(1);setSelected('arXiv.2');viewport.current?.scrollTo({top:0,left:0,behavior:'smooth'});}
 const related=(keys:Set<string>)=>map.nodes.filter(n=>keys.has(n.key));
 return <section className="research-map-section" id="research-map" aria-labelledby="map-heading"><div className="map-intro"><div><span className="section-kicker">Research atlas / 2022–2026</span><h2 id="map-heading">Every work. A connected story.</h2><p>Follow a research question from the system that made it possible to the people and consequences it reveals.</p></div><span className="map-count"><strong>{map.nodes.length}</strong>works & projects</span></div>
 <div className="map-controls"><ToggleGroup className="map-themes" value={[theme]} onValueChange={v=>{if(v[0]){setTheme(v[0] as string);viewport.current?.scrollTo(0,0)}}} aria-label="Filter research by theme">{themes.map(t=><ToggleGroupItem key={t.key} value={t.key} className="theme-control" style={{'--theme-color':t.color} as CSSProperties}><span className="theme-dot"/>{t.label}</ToggleGroupItem>)}</ToggleGroup><div className="map-toolbar"><label className="map-search"><span className="sr-only">Search research titles, authors, venues, or topics</span><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search a title, topic, or venue…"/></label><span className="matching" role="status">{filtered.length} of {map.nodes.length} works</span><ToggleGroup className="view-switch" value={[view]} onValueChange={v=>v[0]&&setView(v[0] as string)} aria-label="Research view"><ToggleGroupItem value="map">Map</ToggleGroupItem><ToggleGroupItem value="list">List</ToggleGroupItem></ToggleGroup><Button className="map-button" onClick={reset}>Reset</Button></div></div>
 {view==='map'?<><div className="map-help"><p>Select a work to trace its earlier and later connections. Scroll to explore the full map.</p><div><Button className="map-button" aria-label="Zoom out" disabled={zoom<=1} onClick={()=>setZoom(z=>Math.max(1,z-.2))}>−</Button><span>{Math.round(zoom*100)}%</span><Button className="map-button" aria-label="Zoom in" disabled={zoom>=1.6} onClick={()=>setZoom(z=>Math.min(1.6,z+.2))}>+</Button></div></div><div className="map-viewport" ref={viewport} tabIndex={0} role="region" aria-label="Scrollable research timeline"><div style={{width:1220*zoom,height:layout.height*zoom}}><div className="map-canvas" style={{width:1220,height:layout.height,transform:`scale(${zoom})`,transformOrigin:'top left'}}>
 {[2022,2023,2024,2025,2026].map((year,i)=><div className="map-year" key={year} style={{left:162+i*208}}>{year}<div style={{height:layout.height-50}}/></div>)}
 {layout.bands.map(b=><div className="map-band" key={b.label} style={{top:b.y,height:b.height}}><div><strong>{b.label}</strong><span>{b.sub}</span></div></div>)}
 <svg className="connections" width="1220" height={layout.height} aria-hidden="true"><defs><marker id="map-arrow" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0L8 4L0 8Z" fill="context-stroke"/></marker></defs>{map.edges.map((e,i)=>{const a=layout.positions[e.from],b=layout.positions[e.to];if(!a||!b)return null;const isTraced=(e.from===selected||ancestors.has(e.from)||descendants.has(e.from))&&(e.to===selected||ancestors.has(e.to)||descendants.has(e.to));const sameYear=a.x===b.x;const path=sameYear?`M${a.x+182},${a.y+25} C${a.x+202},${a.y+25} ${b.x+202},${b.y+25} ${b.x+182},${b.y+25}`:`M${a.x+182},${a.y+25} C${(a.x+b.x)/2+91},${a.y+25} ${(a.x+b.x)/2+91},${b.y+25} ${b.x-4},${b.y+25}`;return <path key={i} d={path} fill="none" stroke={isTraced?'#d4ef8a':'#52677f'} strokeWidth={isTraced?2.2:1} opacity={isTraced?.85:.4} markerEnd="url(#map-arrow)"/>})}</svg>
 {filtered.map(n=>{const pos=layout.positions[n.key];if(!pos)return null;const p=works.find(p=>p.id===n.publicationId)!;const isSelected=n.key===selected;const isRelated=ancestors.has(n.key)||descendants.has(n.key);return <button key={n.key} className={`map-node ${isSelected?'is-selected':''} ${isRelated?'is-related':''} ${n.key.startsWith('arXiv')||n.key.startsWith('pat')||n.key==='project-vbc'?'is-provisional':''}`} style={{left:pos.x,top:pos.y,'--node-color':colors[n.color]||n.color} as CSSProperties} onClick={()=>pick(n.key)} aria-pressed={isSelected} aria-controls="research-detail" aria-label={`${p.title.replace('✦','')}. ${p.kind}. Show research details.`}><span className="node-label">{n.label}</span><span className="node-meta">{n.key==='project-vbc'?'Under review':n.key.startsWith('arXiv')?'Preprint':n.key.startsWith('pat')?'Patent':p.venue.split(' · ')[0].slice(0,27)}</span>{p.selected&&<span className="node-star" aria-label="Selected work">✦</span>}</button>})}
 {!filtered.length&&<div className="map-empty">No works match this search. Try another title or reset the filters.</div>}
 </div></div></div></>:<div className="map-list">{filtered.length?filtered.map(n=>{const p=works.find(p=>p.id===n.publicationId)!;return <Button key={n.key} className={'map-list-item '+(selected===n.key?'is-selected':'')} onClick={()=>pick(n.key)} aria-pressed={selected===n.key}><span>{p.kind.replace(/\[.*?\] · /,'')}</span><strong>{p.title.replace('✦','')}</strong><span>{p.venue}</span></Button>}):<p className="map-empty">No works match this search. Try another title or reset the filters.</p>}</div>}
 <div className="map-legend"><span><i className="legend-line"/> Research development</span><span><i className="legend-line traced"/> Selected lineage</span><span>✦ Selected work</span><span>Dashed border: preprint, patent, or work under review</span></div>
 <div className="research-detail" id="research-detail" aria-live="polite" aria-atomic="true"><div className="detail-main"><span className="detail-kicker">{paper.kind.replace(/\[.*?\] · /,'')}{!visible.has(selected)&&' · outside current filter'}</span><h3>{paper.title.replace('✦','')}</h3><p className="detail-authors">{paper.authors}</p><p className="detail-venue">{paper.venue}</p><p>{paper.note}</p><div className="detail-links">{paper.url&&<a href={paper.url}>Read the work ↗</a>}{selected==='arXiv.2'&&<a href="https://github.com/KindOPSTAR/QualiGPT">Source code ↗</a>}{selected==='c.4'&&<a href="https://github.com/KindOPSTAR/VRMN-bD">Dataset & models ↗</a>}</div></div><div className="lineage-panel"><div><h4>Earlier work <span>{ancestors.size}</span></h4>{ancestors.size?related(ancestors).map(n=><Button className="lineage-link" key={n.key} onClick={()=>pick(n.key)}>↖ {n.label}</Button>):<p>No earlier connection recorded.</p>}</div><div><h4>Later developments <span>{descendants.size}</span></h4>{descendants.size?related(descendants).map(n=><Button className="lineage-link" key={n.key} onClick={()=>pick(n.key)}>↗ {n.label}</Button>):<p>No later connection recorded.</p>}</div></div></div>
 <p className="map-source-note">Connections describe the research trajectories presented on my earlier website, rather than bibliographic citations. The reasoning project is shown separately while under review.</p></section>
}
